Issue 215 - Add query param to the behavior page
filecoin-project/system-test-matrix pull request #229
Opened 2021-12-08 15:18 UTC by mstojanovicbloxico

## Description

Use behaviour ID as query param on behaviours page.

- [x] I have performed a self-review of this code and spelling
- [ ] I have added comments in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Additional information

![Screenshot from 2021-12-08 16-18-06](https://user-images.githubusercontent.com/85557938/145233688-a8361fbd-a83d-408d-b3ce-85cbf6e42ea0.png)

2021-12-09 14:00 UTC, toljaEmbroker requested changes

2021-12-09 14:00 UTC, toljaEmbroker commented on frontend/apps/web/src/pages/behaviors.tsx
> +        behavior.id === new URLSearchParams(window.location.search).get('id'),
also use this as a queryParam standard (@mstojanovicbloxico @Vojimirovich )
```
import qs from 'query-string'
import {useLocation} from 'react-router-dom'

......
interface BehaviorQueryParams {
 id?: string
}
.......
const location = useLocation()
const {id: behaviorId} : BehaviorQueryParams = qs.parse(location.search)
......
navigate({
                    search: `?{qs.stringify({...queryParams, id: data.id})`,
                  })
```

2021-12-10 11:05 UTC, mstojanovicbloxico commented on frontend/apps/web/src/pages/behaviors.tsx
> +        behavior.id === new URLSearchParams(window.location.search).get('id'),
Done and Done

2021-12-10 12:52 UTC, aleksaToljic approved these changes

2021-12-10 13:36 UTC, merged