Feat/issue 43 update table component
filecoin-project/system-test-matrix pull request #59
Opened 2021-11-15 19:05 UTC by Vojimirovich

2021-11-16 19:35 UTC, aleksaToljic requested changes

2021-11-16 19:35 UTC, aleksaToljic commented on frontend/apps/web/package.json
> -    "prebuild": "concurrently \"yarn generate:routes\" \"yarn generate:behaviors\"",
This shouldn't be in commit

2021-11-16 19:35 UTC, aleksaToljic commented on frontend/packages/ui/src/Table.tsx
> +        <TableHeaderRow>
You lost th here, we should return it.

2021-11-17 02:35 UTC, Vojimirovich commented on frontend/apps/web/package.json
> -    "prebuild": "concurrently \"yarn generate:routes\" \"yarn generate:behaviors\"",
Done

2021-11-17 02:36 UTC, Vojimirovich commented on frontend/packages/ui/src/Table.tsx
> +        <TableHeaderRow>
Returned it, thanks for noticing!

2021-11-17 18:32 UTC, aleksaToljic approved these changes

2021-11-17 18:32 UTC, merged